services:
  - type: web
    plan: free
    name: app
    runtime: docker
    envVars:
      - key: DSN
        fromDatabase:
          name: db
          property: connectionString
      - key: MIGRATIONS
        value: file://migrations

databases:
  - name: db
    postgresMajorVersion: "16"
    plan: free


